package fr.coaching.maseance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiplomeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiplomeAllPropertiesEquals(Diplome expected, Diplome actual) {
        assertDiplomeAutoGeneratedPropertiesEquals(expected, actual);
        assertDiplomeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiplomeAllUpdatablePropertiesEquals(Diplome expected, Diplome actual) {
        assertDiplomeUpdatableFieldsEquals(expected, actual);
        assertDiplomeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiplomeAutoGeneratedPropertiesEquals(Diplome expected, Diplome actual) {
        assertThat(expected)
            .as("Verify Diplome auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiplomeUpdatableFieldsEquals(Diplome expected, Diplome actual) {
        assertThat(expected)
            .as("Verify Diplome relevant properties")
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()))
            .satisfies(e ->
                assertThat(e.getNbAnneesEtudePostBac()).as("check nbAnneesEtudePostBac").isEqualTo(actual.getNbAnneesEtudePostBac())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiplomeUpdatableRelationshipsEquals(Diplome expected, Diplome actual) {
        assertThat(expected)
            .as("Verify Diplome relationships")
            .satisfies(e -> assertThat(e.getCoachExperts()).as("check coachExperts").isEqualTo(actual.getCoachExperts()));
    }
}
