package fr.coaching.maseance.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OffreCoachMediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreCoachMediaAllPropertiesEquals(OffreCoachMedia expected, OffreCoachMedia actual) {
        assertOffreCoachMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertOffreCoachMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreCoachMediaAllUpdatablePropertiesEquals(OffreCoachMedia expected, OffreCoachMedia actual) {
        assertOffreCoachMediaUpdatableFieldsEquals(expected, actual);
        assertOffreCoachMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreCoachMediaAutoGeneratedPropertiesEquals(OffreCoachMedia expected, OffreCoachMedia actual) {
        assertThat(expected)
            .as("Verify OffreCoachMedia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreCoachMediaUpdatableFieldsEquals(OffreCoachMedia expected, OffreCoachMedia actual) {
        assertThat(expected)
            .as("Verify OffreCoachMedia relevant properties")
            .satisfies(e -> assertThat(e.getUrlMedia()).as("check urlMedia").isEqualTo(actual.getUrlMedia()))
            .satisfies(e -> assertThat(e.getTypeMedia()).as("check typeMedia").isEqualTo(actual.getTypeMedia()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOffreCoachMediaUpdatableRelationshipsEquals(OffreCoachMedia expected, OffreCoachMedia actual) {
        assertThat(expected)
            .as("Verify OffreCoachMedia relationships")
            .satisfies(e -> assertThat(e.getOffreCoach()).as("check offreCoach").isEqualTo(actual.getOffreCoach()));
    }
}
